# Generated by Django 5.2.4 on 2025-07-13 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locations',
            name='user',
        ),
        migrations.AddField(
            model_name='locations',
            name='trip',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='tours.trip'),
        ),
    ]
