# Generated by Django 5.2.4 on 2025-07-16 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_remove_locations_user_locations_trip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locations',
            name='trip',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='tours.trip'),
            preserve_default=False,
        ),
    ]
