# Generated by Django 5.2.4 on 2025-07-16 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0003_alter_locations_trip'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('visit_time', models.DateField()),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='trip',
            name='locations',
            field=models.ManyToManyField(blank=True, related_name='trips', to='tours.location'),
        ),
        migrations.DeleteModel(
            name='Locations',
        ),
    ]
