# Generated by Django 5.2.4 on 2025-07-16 11:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0005_location_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='visit_time',
        ),
        migrations.AddField(
            model_name='location',
            name='close_time',
            field=models.TimeField(default=datetime.time(10, 0)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='open_time',
            field=models.TimeField(default=datetime.time(19, 0)),
            preserve_default=False,
        ),
    ]
