# Generated by Django 5.2.4 on 2025-07-18 13:19

import django.db.models.deletion
import tours.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0006_remove_location_visit_time_location_close_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category_breakdown', models.JSONField(validators=[tours.models.validate_category_breakdown])),
                ('generated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('visitor', 'Visitor'), ('guide', 'Guide'), ('admin', 'Admin')], default='visitor', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='expense',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='positive_amount'),
        ),
        migrations.AddConstraint(
            model_name='trip',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='end_date_gte_start_date'),
        ),
        migrations.AddField(
            model_name='expensesummary',
            name='trip',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='summary', to='tours.trip'),
        ),
    ]
