# Generated by Django 5.2.4 on 2025-07-22 12:08

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0007_expensesummary_alter_user_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensesummary',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10),
        ),
    ]
