# Generated by Django 5.2.4 on 2025-08-02 13:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0011_expense_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='enrolled_visitors',
            field=models.ManyToManyField(blank=True, related_name='enrolled_trips', to=settings.AUTH_USER_MODEL),
        ),
    ]
